### ISSUE TITLE
Incorrect Profile Shown On Hover

### ISSUE THREAD

**Issue by pdiamond-op** [elk-zone/elk#1453] opened 2023-01-25 16:02 UTC
In some situations, the incorrect user profile will be shown when hovering over a user in a threaded conversation. I haven't been able to narrow down exactly when it occurs, but it appears that the longer and more nested the thread is, the more likely it is to occur. Posts with no replies and posts with just 1 or 2 unnested replies are correct (at least all the ones I checked).
One example I have is here https://elk.zone/infosec.exchange/@Curator@mastodon.art/109750190080563250
In this example, you can see I am hovering over the user "Mirre" and the profile for "Nick Stevens Graphics" is displayed. Nick Stevens is part of this thread, so it doesn't appear to be displaying totally random profiles, just the incorrect ones from the same thread.
It is also inconsistent. In the second screenshot I am hovering over the "Mirre" user again, but the profile for "ratfactor" is displayed.
If I click on the "Mirre" user in the thread I am taken to the correct "Mirre" user profile page, it's just the hover that is incorrect. (Clicking on the user from the hover popup doesn't do anything, regardless of whether it's the correct user or not)

![image](https://user-images.githubusercontent.com/113446450/214610624-f7059b47-d9c7-405b-9dec-fb52d992e3b1.png)

![image](https://user-images.githubusercontent.com/113446450/214612898-e64ba885-2154-421f-8044-3cc0d7713f73.png)

**Comment by bool-kit** [comment] 2023-01-26 14:15
Looks like a duplicate of #1363.

**Closed** 2023-02-04 22:49 UTC
