### ISSUE TITLE
CORS issue on fetching `/nodeinfo/2.0`

### ISSUE THREAD

**Issue by jibsaramnim** [elk-zone/elk#1522] opened 2023-01-29 23:52 UTC
One of the earlier automatic requests made to the server you're looking at through Elk fails due to its CORS policy. I noticed this with my locally running version, but can confirm this is also the case on `main.elk.zone`.

```log
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://m.webtoo.ls/nodeinfo/2.0. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
```

The endpoint seems mostly just informative regarding what the selected server is running in terms of version and whatnot, but as Elk does try to read from it, I thought I'd report it here.

**Comment by Shinigami92** [comment] 2023-01-30 11:57
I can confirm this, but just didn't had time to open an issue for this 👍

**Comment by ayoayco** [comment] 2023-03-23 12:16
@Shinigami92 did you see a JS error being thrown due to this?

**Comment by Shinigami92** [comment] 2023-03-23 12:21
I had an issue in the browser console. Need to check again when I'm back to a PC

**Comment by Shinigami92** [comment] 2023-03-23 12:37
@ayoayco 

![image](https://user-images.githubusercontent.com/7195563/227205832-d71d64b5-2865-4c51-a83c-c512ab426e3c.png)

**Comment by ayoayco** [comment] 2023-03-23 12:59
Thanks!! For additional context, this is the endpoint "used for advertising software name and version, protocols, usage statistics, and whether registrations are open." https://docs.joinmastodon.org/dev/routes/#nodeinfo

**Comment by sxzz** [comment] 2023-03-23 22:40
See https://github.com/mastodon/mastodon/issues/23135

**Comment by Shinigami92** [comment] 2023-10-16 11:46
https://github.com/mastodon/mastodon/commit/23f8e93c6405277515d018d4ff2d550fe64ac159 was merged
I assume it will land in Mastodon v4.2.2

I will close this PR as done

**Closed by Shinigami92** 2023-10-16 11:46 UTC
Labels: c: bug, s: pending triage
