### ISSUE TITLE
"Uncaught (in promise) Error: Could not log into account." after signing in

### ISSUE THREAD

**Issue by mkhl** [elk-zone/elk#1021] opened 2023-01-12 19:06 UTC
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [x] I am willing to provide a PR.

### Describe the bug

reproduction:
1. i click "sign in", select my instance, click "sign in"
2. in my instance's oauth dialog, i click "authorize"

expected outcome:
i get redirected to elk home and see my timeline

actual outcome:
i get redirected to `https://elk.zone/signin/callback?server=social.treehouse.systems&token=…vapid_key=…%3D` and the main content stays empty, including when i go to "home", "conversations" or the other lists.
the browser console shows an error with the message: "Uncaught (in promise) Error: Could not log into account."

### Reproduction video or screenshot

![image](https://user-images.githubusercontent.com/505/212155986-cdc2496f-9f16-48b8-85d3-3f564e079241.png)

the log message from the browser console:
```
Uncaught (in promise) Error: Could not log into account.
    NuxtJS 48
        Bu
        ju
        af
        value
        promise callback*get/<
        mI
        Rw
        promise callback*Rw/<
        Rw
        callHookWith
        callHook
        deferHydration
        onResolve
        promise callback*It
        onResolve
        si
        resolve
        registerDep
        promise callback*registerDep
        x
        f
        d
        h
        f
        d
        h
        f
        d
        h
        f
        d
        h
        f
        ke
        W
        run
        update
        z
        x
        f
        ke
        W
        run
        update
        z
        x
        f
        ke
undefined:1:89709
```

### Additional Context

browser: firefox 108.0.2
instance: social.treehouse.systems

login used to work but broke at some point (i think in the version just before 0.3.0?)

now it keeps happening after deleting the app token and elk local data

**Comment by vibragiel** [comment] 2023-01-13 10:01
Duplicate of #934 .

**Closed** 2023-01-13 10:07 UTC
Labels: c: bug, s: pending triage
