### ISSUE TITLE
Translation icon appears when in the user's current language

### ISSUE THREAD

**Issue by osfanbuff63** [elk-zone/elk#1433] opened 2023-01-24 23:02 UTC
Elk is incorrectly showing the `Translate post` text when the post is in the correct language currently (in my case, English).

![image](https://user-images.githubusercontent.com/91388253/214440005-1e410574-745a-4cf5-ab54-8f0ca2fa9415.png)
(Note: I also use the Catppuccin Mocha theme for Elk, aka https://github.com/catppuccin/elk)

I seem to be able to reproduce this with one Calckey user and no other posts. [Here's the original post](https://i.calckey.cloud/notes/9aec8gkkb7) (in Calckey) and [here's that same post in Elk](https://elk.zone/i.calckey.cloud/notes/9aec8gkkb7). 

**Steps to Reproduce**:
1. Open the two links in the above paragraph in different tabs.
2. Make sure that your language in Elk is set to English.
3. See that the Elk link shows the Translate post text, while the post is clearly in English.

**Comment by niklaswolf** [comment] 2023-02-12 11:05
I can not reproduce this, especially because the link to the post in Elk is not working anymore (seems like the account moved).

>  seem to be able to reproduce this with one Calckey user and no other posts
I have a guess that this particular user has/had set the wrong language in his post, so the post seemed to be english obviously, but had another language set. This is when Elk's translation feature triggers.

I suggest closing this issue.

**Closed** 2023-05-18 11:34 UTC
Labels: c: bug, s: awaiting more info
