### ISSUE TITLE
"Enter Elk" and allow notifications messages keep reappearing 

### ISSUE THREAD

**Issue by jensimmons** [elk-zone/elk#2493] opened 2023-12-01 16:09 UTC
Lately, every time I load any page at elk.zone/* the overlay appears that declares that Elk is in preview. 

<img width="470" alt="Screenshot 2023-12-01 at 11 07 39 AM" src="https://github.com/elk-zone/elk/assets/108474/a9070da8-3722-4adb-ac87-a298902db2a2">

This used to only appear once, after logging in.

Also, every time I go to my Notifications feed, there's a request to allow notifications. I can dismiss it, but it reappears if I load the page. 

<img width="621" alt="Screenshot 2023-12-01 at 11 09 04 AM" src="https://github.com/elk-zone/elk/assets/108474/ba1ee2c5-b77b-41fd-b21b-4e6a38d0780b">

**Comment by userquin** [comment] 2023-12-01 18:02
browser and OS? maybe you have some options disabled, closing both welcome and notification will store a flag in local storage

**Comment by patak-dev** [comment] 2023-12-01 18:05
I tried to reproduce it too (in safari and chrome) with no luck, both logged in and logged out.

**Comment by patak-dev** [comment] 2024-01-09 09:02
@jensimmons, are you still experiencing this issue? I tested in Safari Version 17.2.1 (19617.1.17.11.12) and I couldn't reproduce it.

**Comment by shuuji3** [comment] 2024-01-21 07:38
I also couldn't reproduce this in Safari Version 17.0 (19616.1.27.211.1) on macOS.

When we click the "Enter App" button, Elk sets `elk-first-visit` value to `false` in Local Storage and won't show the dialog twice with this value. I'm wondering if some Safari preference or extension blocks updating Local Storage.

![Screenshot 2024-01-21 at 16 32 36](https://github.com/elk-zone/elk/assets/1425259/9acce0ba-a31a-4f64-aa00-713a7d864767)

**Comment by patak-dev** [comment] 2024-01-21 07:45
@jensimmons let's close this issue as I think this was something related to the safari beta version you were using. Please let us know if you still experience this and we'll reopen it 🙏🏼 
Thanks again for reporting these issues you see ❤️

**Closed by patak-dev** 2024-01-21 07:45 UTC
Labels: c: bug, s: pending triage
