### ISSUE TITLE
Continually prompts "New Elk update available!" while on 0.11.0

### ISSUE THREAD

**Issue by nickurak** [elk-zone/elk#2619] opened 2024-02-24 22:08 UTC
Elk.zone for me is continuously saying "New Elk update available!". Hitting the button to update does cause the page to reload, but later in the day the message will pop up again.

![image](https://github.com/elk-zone/elk/assets/1140821/dcfd862e-9af0-491f-aa5c-103115e178db)

**Comment by rlmcneary2** [comment] 2024-02-29 12:55
Happening on Firefox Beta channel, both desktop (windows, mac) and mobile (android). Windows FF version 124.0b4 (64-bit). I have manually uninstalled the web worker and reloaded and the problem persists.

**Comment by userquin** [comment] 2024-03-07 09:57
Can you try with latest version? Maybe the first time the update button will not work, we had a regression in pwa plugin. The app should auto-update, check the version  in settings > about , ot should be 0.12.1, once updated if the update button still there refresh the page.

**Comment by rlmcneary2** [comment] 2024-03-07 13:08
I've had 0.12.1 installed since yesterday and the update button no longer reappears.

**Comment by shuuji3** [comment] 2024-03-22 15:50
I hope this issue was fixed by 0.12.1. Please feel free to reopen if the same issue still happens.

**Closed by shuuji3** 2024-03-22 15:50 UTC
Labels: c: bug, s: accepted
