### ISSUE TITLE
Add the ability to browse the public local feed of another instance

### ISSUE THREAD

**Issue by ZMYaro** [elk-zone/elk#1646] opened 2023-02-05 22:11 UTC
Right now, the URL structure for your instance's local feed is `/[your instance]/public/local`.  If you replace `[your instance]` with another instance, you just get redirected back to `/home`.  Instead, you should be able to browse another instance's public local feed.

**Comment by boehs** [comment] 2023-02-06 04:09
duplicate of ##972

**Closed by boehs** 2023-02-06 04:09 UTC
Labels: s: pending triage
