### ISSUE TITLE
[Feature request] Fetch post replies from remote instance

### ISSUE THREAD

**Issue by KaKi87** [elk-zone/elk#1500] opened 2023-01-28 08:27 UTC
Hello,

When reading a post from a remote instance, it would be nice for the Elk front-end to fetch its replies from said remote instance when the local one don't have those.

Thanks

**Comment by ayoayco** [comment] 2023-01-28 08:34
Hi @KaKi87 thanks for reporting. Closing this one as duplicate of #996 – pls see if you can give insight there instead

**Closed** 2023-01-28 08:34 UTC
Labels: s: pending triage
