### ISSUE TITLE
feat: take advantage of the 4K viewport

### ISSUE THREAD

**Issue by iamdtms** [elk-zone/elk#2504] opened 2023-12-06 13:19 UTC
Please scale elk screen for 4K viewports, if it matters. 

Order could be multiple cols or anything arranged what take advantage of the free space. 

<img width="1920" alt="Képernyőkép 2023-12-06 140106" src="https://github.com/elk-zone/elk/assets/11964785/4f67029a-3ad8-481d-8c04-fe626782a451">

<img width="782" alt="Képernyőkép 2023-12-06 140150" src="https://github.com/elk-zone/elk/assets/11964785/1c9b13d0-426e-4f8e-b174-9b51e53b7574">

Thank you, looking forward to your answer/possible discussion about it: **@iamdtms**

**Comment by HawtinZeng** [comment] 2023-12-18 14:02
@antfu I think this feat matters too, how do u think?

**Comment by patak-dev** [comment] 2024-01-09 15:32
If we do something with the extra space, it would probably be to have a multi-column view https://github.com/elk-zone/elk/issues/1404. I think we can close this issue and discuss there.  There are other proposals like https://github.com/elk-zone/elk/issues/1866. Closing as duplicate of these

**Closed by patak-dev** 2024-01-09 15:32 UTC
Labels: s: pending triage

**Comment by HawtinZeng** [comment] 2024-01-09 15:35
It's ok.



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 9, 2024 23:32 PM
To: ***@***.***&gt;;
Cc: "Hawtin ***@***.******@***.***&gt;;
Subject: Re: [elk-zone/elk] feat: take advantage of the 4K viewport (Issue#2504)




 
If we do something with the extra space, it would probably be to have a multi-column view #1404. I think we can close this issue and discuss there.  There are other proposals like #1866. Closing as duplicate of these
