### ISSUE TITLE
Transparent navigation bar on Android

### ISSUE THREAD

**Issue by toniengelhardt** [elk-zone/elk#1770] opened 2023-02-16 19:28 UTC
Hey guys,

let's drop some stars and comments on these Chrome issues to once and for all get rid of the annoying navigation bar color on Android:

https://bugs.chromium.org/p/chromium/issues/detail?id=1001394

https://bugs.chromium.org/p/chromium/issues/detail?id=797527

https://github.com/w3c/manifest/issues/804

Goal is to either be able to draw behind it with `safe-area-inset` like on iOS or set the color dynamically via meta tag like the status bar. It should be an easy implementation and until this is resolved PWAs will always be inferior to native apps IMO.

![Screenshot_20230216-191916 (1)](https://user-images.githubusercontent.com/2703233/219466524-412f02c0-931b-4130-9ff3-90dadfd2c2eb.png)

**Comment by edimitchel** [comment] 2023-02-16 23:54
Duplicate of #368

**Closed** 2024-02-26 10:30 UTC
Labels: s: pending triage
