### ISSUE TITLE
The menu bar may keep flashing if scrolling up and then scrolling down slowly

### ISSUE THREAD

**Issue by zxch3n** [elk-zone/elk#1549] opened 2023-02-01 04:23 UTC
https://user-images.githubusercontent.com/18425020/215945895-ac6fda84-a001-4426-8f4b-2d01bef4762e.MOV

**Comment by boehs** [comment] 2023-02-06 04:32
I'm gonna wager this is a duplicate of #1082

**Closed by boehs** 2023-02-06 04:32 UTC
Labels: c: bug, s: pending triage
