### ISSUE TITLE
Toots combined?

### ISSUE THREAD

**Issue by limako** [elk-zone/elk#2466] opened 2023-11-10 21:20 UTC
I was looking at notifications and saw that two toots got confabulated somehow: 
![wordweavers](https://github.com/elk-zone/elk/assets/6980760/21465c58-21d3-43bd-95ba-0ad0d605e8bf)

Here are the two toots:
  https://wandering.shop/@stevendbrewer/111388140483582327
  https://wandering.shop/@stevendbrewer/111388102788347145

**Comment by SteveDinn** [comment] 2023-11-29 14:05
I have seen this from time to time as well, and in fact, came here to report this bug just now. You can see in my screenshot how the first notification has the text of the post (minus the mentions) from the second notification. I'm using an up-to-date [main.elk.zone](https://main.elk.zone) as of this morning (2023-11-29).

![image](https://github.com/elk-zone/elk/assets/3911507/fc0551fc-168e-443c-8398-37352eace284)

**Comment by SteveDinn** [comment] 2023-11-29 14:07
Interesting side note: In the first notification in that screenshot, the mention is out of place.

The mention of "coffeegeek" should be In line with the last sentence of the first paragraph: *"Maybe also ___ might be interested in this."*

**Comment by SteveDinn** [comment] 2023-11-29 14:10
Also an interesting side note: a hard re-load of the page makes the notifications look correct again. With respect to both the run-together posts and the placement of the mentions.

**Comment by sentience** [comment] 2023-12-07 05:26
Duplicate of #2216

**Closed** 2024-01-09 17:10 UTC
Labels: c: bug, s: pending triage
