### ISSUE TITLE
Suspend avatar for slow network

### ISSUE THREAD

**Issue by edimitchel** [elk-zone/elk#1039] opened 2023-01-13 00:54 UTC
### Pre-Checks

- [X] Check that there isn't [already an issue](https://github.com/elk-zone/elk/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/elk-zone/elk/discussions) or join our [Discord Chat Server](https://chat.elk.zone).
- [X] Providing a screenshot or video to reproduce the issue or show visually what was meant.
- [ ] I am willing to provide a PR.

### Describe the bug

When I use the phone for using Elk, and when I come to a new user which I did never load his avatar, I see the alt text instead of his image (because it's not loaded).

I think we could easily show a placeholder image the time the image is fully loader.
I dunno if we could get a pixel image of the avatar to show a blury avatar instead of a dumb placeholder?

### Reproduction video or screenshot

![firefox_n8Yu99a66Q](https://user-images.githubusercontent.com/2922851/212211909-c61dba7c-5691-4ee8-a100-d8c17d8d8635.gif)

**Comment by ZMYaro** [comment] 2023-01-13 00:55
Or even just keep the skeleton UI placeholder circle until the avatar loads in.

**Comment by alexzhang1030** [comment] 2023-01-13 02:14
Seems like it fixed in #327 , and I can't reproduce it, can you give me more infomations?

**Comment by alexzhang1030** [comment] 2023-01-13 02:15
Seems like it fixed in #327 , and I can't reproduce it, can you give me more infomations?

**Comment by edimitchel** [comment] 2023-01-13 08:10
> Seems like it fixed in #327 , and I can't reproduce it, can you provide more infomations?

I don't think it related.
Daniel added a mechanism in case of error, we should do the same for loading I guess

**Closed** 2023-01-13 09:23 UTC
Labels: c: bug, s: pending triage
