### ISSUE TITLE
Elk.zone Home tab shows incorrect name

### ISSUE THREAD

**Issue by SympathyTea** [elk-zone/elk#1776] opened 2023-02-17 13:49 UTC
This is my first issue here, bear with me
this is semi-consistent behavior (thus why i am making this issue) and I'm unsure if this has been addressed or not nor do I have a concrete fix
Currently on Firefox with Windows 10

How to replicate (very hit or miss):
Go to https://elk.zone/home
Click someone's profile, I specifically used someone from my own instance.
Title changes to "Posts (Username here)"
Go back to home
Title of the tab will get "stuck" on a name, and wont change back.
![image](https://user-images.githubusercontent.com/116274772/219671205-fa4efd1d-72f7-4389-a731-1ed942685480.png)
(The solid black tab is the currently selected tab, and the "Home | Elk" tab is a demonstration on what this tab's title should look like.)

If this is already been posted before, I'm incredibly sorry, you may feel free to close this issue if needed.

**Comment by userquin** [comment] 2023-02-17 20:18
All page titles broken, you need to navigate twice, for example:
- home -> notifications -> home
- home -> notifications -> mention tab -> all notifications tab
- home -> favorites -> home

Maybe the fix (`useHeadFixed`) not required:  there is also `titleTemplate` on `composables/setup.ts` module...

**Comment by ayoayco** [comment] 2023-02-18 09:55
Also adding a scenario going to a List time line to any timeline, the List name is kept as the page title.

**Comment by userquin** [comment] 2023-02-18 10:01
Not yet @ayoayco , navigate to your account, followers, following, followers, then back to notifications or any main from nav bar, I need to check what's happening with `titleTemplate` in `setup.ts` composable (maybe some missing `useHydratedHead`)

**Comment by ayoayco** [comment] 2023-02-18 13:05
@userquin Ah, sorry I meant the scenario in my comment

**Comment by jcrabapple** [comment] 2023-03-22 01:23
I have noticed this as well, in Firefox and Chrome.

**Comment by userquin** [comment] 2023-04-02 14:36
It is a problem with unhead, there is no way to correlate data and route, we are using keep alive. 

All active pages will be on header entries, there is some race condition between deactivated and activated page hooks: https://github.com/unjs/unhead/blob/main/packages/vue/src/runtime/composables/util/clientUseHead.ts#L13

I Will send a PR to fix vue package.

/cc @danielroe maybe you can find another fix ;)

**Comment by userquin** [comment] 2024-09-07 17:14
Closing this, looks like cannot reproduce the problem, feel free to open a new issue if still reproducible (I only test it on Chrome)

**Closed by userquin** 2024-09-07 17:14 UTC
Labels: c: bug
