### ISSUE TITLE
Remember the last used setting for Notifications tab

### ISSUE THREAD

**Issue by edwellbrook** [elk-zone/elk#2425] opened 2023-10-10 08:38 UTC
The "Notifications" tab offers multiple options "All", "Mentions" (and now other activity types).

When I click on "Notifications" in the sidebar, I want to be taken to my last selection (i.e. if I previously changed the view to "Mentions" only, when I click on "Notifications" in the sidebar, I want to return to the mentions only view).

Defaulting to "All" is broadly fine, but as I only ever want to see mentions (and not likes, boosts, follows etc.), I need an extra click to show the only view I ever want to see.

Please let me know if you need more info or clarifications.

If this is approved as a reasonable idea and someone with knowledge of the codebase wants to point to where and what should be updated, please let me know. If it's fairly straight-forward, I'd be happy to open a PR myself.

Thanks!

**Comment by Sma11X** [comment] 2023-10-10 10:44
Duplicate of #1058 , maybe you can try to ask on discord for more info

**Closed** 2023-10-17 09:54 UTC
Labels: s: pending triage
