### ISSUE TITLE
When clicking a Mastodon message link, show it within Elk instead of opening a new window on the author's instance

### ISSUE THREAD

**Issue by Kalytis** [elk-zone/elk#2312] opened 2023-08-07 15:51 UTC
For now, Mastodon doesn't allow message-quoting (not debating whether they should or not).

We still like to redirect to another piece of content, sometimes Mastodon posts. The only option is to take the link of the post and paste it in our own post.

But then, once clicking the link, the message opens in another tab, on the instance where the "quoted" post was first sent. Same for links to Mastodon profiles, which prevents us to click on a person's link and follow it directly.

I'd love for Mastodon content links to be opened within Elk, and not through another tab, on an instance on which I'm not connected.

**Comment by Shinigami92** [comment] 2023-08-07 16:18
How would you identify that it is a Mastodon-Instance/Link instead of just a normal URL?

**Comment by Kalytis** [comment] 2023-08-07 16:21
The same way Musk used to block posting any link leading to a Mastodon instance ? (Not a dev, don't know if it's feasible, just suggesting)

**Comment by Shinigami92** [comment] 2023-08-07 16:24
This would mean having a static file containing most popular instances, but wont work for smaller instances.
Would this solve your problem?
It's not impossible :thinking:

**Comment by Kalytis** [comment] 2023-08-07 21:26
Once again, not a dev, not a technical expert, just posting a suggestion.

**Comment by shuuji3** [comment] 2023-08-08 14:08
Thanks for the suggestion. 🙂 

It looks like Elk is fetching the list of servers from https://elk.zone/api/list-servers during the sign-in. While I'm not sure how this data is retrieved but it has good coverage. I'm wondering if we can use this list instead of a static file.

**Comment by shuuji3** [comment] 2023-08-15 07:40
Thanks for sharing. I didn't know this and it looks useful. I checked the user script but it seems that this script applied to all domains and redirected one domain to another. Although this method works if it's installed like the browser extension, we cannot use the same mechanism, because Elk cannot run a script in a different domain.

That said, this script can be used as an option until Elk could have the implementation. Also, this works in other places where Elk is not used.

**Comment by astrojuanlu** [comment] 2023-08-19 07:39
Duplicate of #2049?

**Closed** 2023-10-08 03:16 UTC
Labels: duplicate, c: feature
