### ISSUE TITLE
Add option to disable translation for selected languages

### ISSUE THREAD

**Issue by niklaswolf** [elk-zone/elk#1364] opened 2023-01-21 09:55 UTC
follow up to #1342  and #1358 

As a user I want to have the ability to disable translations for specific languages, for example because I speak more than the default language for my account.

Additional to completely disabling translations (see #1358) there should be an option to disable translations for n languages from a list of all languages. 

I'm willing to work on this feature and provide a PR later on.

**Comment by patak-dev** [comment] 2023-01-21 10:08
Duplicate of https://github.com/elk-zone/elk/issues/1247. @niklaswolf thanks a lot for getting involved! Let's use #1247 to discuss this issue.

**Closed by patak-dev** 2023-01-21 10:08 UTC
Labels: s: pending triage
