### ISSUE TITLE
Add ability to jump between toots with `j` and `k` keys like on Twitter

### ISSUE THREAD

**Issue by nikitavoloboev** [elk-zone/elk#1644] opened 2023-02-05 21:21 UTC
Miss this feature a lot coming from Twitter. `l` for `like` and `b` for bookmark would be perfect to have too. 

I remember there was a PR about this made by someone few months ago but it was never merged.

**Comment by boehs** [comment] 2023-02-06 04:08
duplicate of #39

**Closed by boehs** 2023-02-06 04:08 UTC
Labels: s: pending triage
