### ISSUE TITLE
@user@server inside profile metadata is read as HTML instead of text

### ISSUE THREAD

**Issue by esthedebeste** [elk-zone/elk#2433] opened 2023-10-19 00:40 UTC
I have a bot i made in the metadata of my profile, and this breaks the metadata when i update my profile with elk.

Steps (all within elk): 
- Add a metadata tag to your profile @'ing another account (for me that's `@billie_lyrics@botsin.space`)
- Save
- That same metadata tag turns into html code inside of the edit field
- When you save again after that, that html code is escaped (with `&lt;` and the such) and shows as raw text on your profile.

**Comment by snail-coupe** [comment] 2023-10-21 20:14
I think this is a duplicate of my #1216?

**Comment by esthedebeste** [comment] 2023-10-23 12:34
yep i believe it is 😅

**Closed** 2023-11-27 12:20 UTC
Labels: c: bug, s: pending triage
