### ISSUE TITLE
Better keyboard interaction experience

### ISSUE THREAD

**Issue by Suzie97** [elk-zone/elk#1629] opened 2023-02-05 06:26 UTC
Things like the ⌘ + K, Ctrl + K and ⌘ + /, Ctrl + / are really nice for a keyboard based workflow and I love it. Feels really ergonomic and improves my workflow with the app. The only thing is that I can't figure out a way to interact with individual posts using the keyboard. Like selecting a particular post and opening it, replying to it, boosting it etc. using the keyboard. I can do that in the official mastodon web app.

I'm sorry if this feature already exists and I can't find it. In that case, any help would be appreciated :))

And if this feature does not exist, adding this would make me happy, hehe.

Also, adding Vim keybindings J and K for navigating up and down the timeline would be nice.

**Comment by boehs** [comment] 2023-02-06 04:15
duplicate of #39

**Closed by boehs** 2023-02-06 04:15 UTC
Labels: s: pending triage
