### ISSUE TITLE
Content from multiple posts getting mixed together

### ISSUE THREAD

**Issue by johnsonm** [elk-zone/elk#2216] opened 2023-07-09 13:41 UTC
Occasionally I'm seeing content from multiple posts mixed into one. For instance, I was on my notifications page, and saw "show 1 new item". I clicked the notification text, and saw this:

![image](https://github.com/elk-zone/elk/assets/79751/193f6b3b-60bf-44a6-b19d-dbf620e6c0b9)

That content is mixed together from two posts:

https://social.makerforums.info/@mcdanlj/110678716327637629

https://social.makerforums.info/@mcdanlj/110684361403957499

I haven't yet figured out a way to reproduce this. I've seen something like this on Firefox 114; the screenshot is from Firefox 115 on Linux.

Here's another set of notifications:

![image](https://github.com/elk-zone/elk/assets/79751/910b9827-5e75-46dc-9d68-2d5b6bfcc0b1)

That inserts the wrong hashtag, which it got from this post:

https://social.makerforums.info/@mcdanlj/110684291181195491

**Comment by swaldman** [comment] 2023-09-16 18:14
I'm seeing similar jumblings. Here's a notification. It looks normal, but it is mistaken, in ways very likely to offend authors of the pieces referenced, if this view were somehow published (like, um, here):

<img width="613" alt="Screenshot 2023-09-16 at 2 07 37 PM" src="https://github.com/elk-zone/elk/assets/1733981/f2bea914-0c14-4c46-9133-8ee6a598266a">

The hashtag that attributes authorship is dangerously wrong. Here are the two original posts the notifications feed has somehow fused:

<img width="615" alt="Screenshot 2023-09-16 at 2 08 09 PM" src="https://github.com/elk-zone/elk/assets/1733981/c7019022-e2a6-4310-af08-c860bc6df3bd">

<img width="639" alt="Screenshot 2023-09-16 at 2 07 52 PM" src="https://github.com/elk-zone/elk/assets/1733981/0cad7cc4-2768-462e-9c50-fb820f96098a">

Attributions are correct in the original, hybridized into error under notifications.

**Comment by chrisesimpson** [comment] 2023-10-12 18:24
Same issue here on Elk v0.10.0 in chrome (117.0.5938.149):

![image](https://github.com/elk-zone/elk/assets/176890/69cea87f-c2d7-47b6-b41c-d4db0cf65652)


If I hit F5 to reload I get the correct unmerged version:

![image](https://github.com/elk-zone/elk/assets/176890/92d1854d-6de0-4332-90ce-16edbe02563f)

**Comment by pjohanneson** [comment] 2023-11-06 23:35
I'm seeing this in Elk canary [0bd1209](https://github.com/elk-zone/elk/commit/0bd1209beeb6e3fb62eabf1ff2ebf9a7c80a3d05), using Firefox 119.0.

**Comment by pjohanneson** [comment] 2024-01-03 03:37
This is new. I saw this this evening, using https://github.com/elk-zone/elk/commit/b016320eaff55166d12ed1176fe5bb6868d6c0fd.

Shown initially:
![Screenshot 2024-01-02 at 21-33-08 Elk](https://github.com/elk-zone/elk/assets/21602/a161c60f-5c33-44c0-a583-9bea381dd212)

How it looked after a refresh (how I'd expect it to look):
![Screenshot 2024-01-02 at 21-33-48 Elk](https://github.com/elk-zone/elk/assets/21602/96042cc9-8dd5-4a83-b2ac-a7890d52c82c)

**Comment by HawtinZeng** [comment] 2024-01-07 03:16
I am working on this bug, if anyone else want to solve this bug, please let me know.

**Comment by HawtinZeng** [comment] 2024-01-07 04:08
Can't reproduce this bug, sorry...

**Comment by patak-dev** [comment] 2024-01-09 13:39
@HawtinZeng when you start working on an issue it is better to do it without sending a message to avoid generating many notifications. You can start working directly, and if someone else is also on it, both can later help reviewing things up. It is rare to have much duplication, so it is better to work on things without much sync between contributors.

**Comment by HawtinZeng** [comment] 2024-01-09 13:43
Ok



---Original---
From: ***@***.***&gt;
Date: Tue, Jan 9, 2024 21:39 PM
To: ***@***.***&gt;;
Cc: "Hawtin ***@***.******@***.***&gt;;
Subject: Re: [elk-zone/elk] Content from multiple posts getting mixed together(Issue #2216)




 
@HawtinZeng when you start working on an issue it is better to do it without sending a message to avoid generating many notifications. You can start working directly, and if someone else is also on it, both can later help reviewing things up. It is rare to have much duplication, so it is better to work on things without much sync between contributors.

**Comment by johnsonm** [comment] 2024-06-21 19:36
Started happening again recently on main.elk.zone — now on Firefox 127.0 on Fedora.

**Comment by jeremiahlee** [comment] 2024-09-13 09:02
I can confirm this is still happening in v0.14.0.
![Screenshot 2024-09-13 at 10 56 55](https://github.com/user-attachments/assets/fc3ab2bd-82a9-43d7-a557-496b25c0567f)

The 2 posts merged: https://alpaca.gold/@Jeremiah/113126698660780340 and https://alpaca.gold/@Jeremiah/113126238688912496

The intermixing always seems to be around when there is a special part of the post, such as an emoji image rendering, a user mention, or a hashtag. Refreshing Elk in the browser then renders the notifications correctly.

**Comment by palant** [comment] 2024-10-19 09:54
I can also see this in v0.15.1. The underlying data is correct – filtering will show the same notification correctly. This appears to be an issue with updating Vue display when new notifications are loaded. The HTML structure is all wrong:

```html
<span class="content-rich line-compact" dir="auto" lang="en">
  <p dir="auto">
    <span class="h-card">Mentions of favorited status</span>
    <span class="h-card"><p dir="auto">Favorited status contents</p></span>
    Contents of unrelated status
  </p>
  <p></p>
  <p>Further contents of unrelated status</p>
</span>
```

**Comment by shuuji3** [comment] 2024-10-19 12:54
Thanks, it's difficult to debug this issue because it's difficult to reproduce, so that kind of analysis is very helpful.

From the above snippet, there seems to be an issue with the `StatusBody` component or related place:
https://github.com/elk-zone/elk/blob/main/components/status/StatusBody.vue

**Comment by palant** [comment] 2024-10-19 21:51
> Thanks, it's difficult to debug this issue because it's difficult to reproduce, so that kind of analysis is very helpful.

You can reproduce this kind of messed up list update:

1. Open https://deploy-preview-3005--elk-zone.netlify.app/notifications (maybe switch to Home and back to Notifications to reset notifications count).
2. Search https://universeodon.com/@elkdev/112762809691433709 in your regular Mastodon account and favorite it.
3. On https://deploy-preview-3005--elk-zone.netlify.app/notifications click “Show 1 new item”
4. Search https://universeodon.com/@elkdev/112305596297137117 in your regular Mastodon account and favorite it.
5. On https://deploy-preview-3005--elk-zone.netlify.app/notifications click “Show 1 new item”

Rather than seeing two favorited statuses you’ll see only one, with incomplete text:

![A “Yellow Flag favourited your post” notification showing a single dancing blobcat. It’s followed up by a notification about a post by terribleandres](https://github.com/user-attachments/assets/63159355-e99c-49cc-b2e4-d420bf6c175c)

Reloading the page results in correct display:

![A “Yellow Flag favourited your post” notification showing five dancing blobcats. It’s followed up by another “Yellow Flag favourited your post” notification and then by a notification about a post by terribleandres](https://github.com/user-attachments/assets/1e7a8fbe-a69c-4418-b553-716d191fabed)

You can undo the favorites to repeat the whole process. It’s 100% reproducible for me.

**Closed** 2024-10-26 03:40 UTC
Labels: c: bug
